### ISSUE TITLE
CI?

### ISSUE THREAD

**Issue by jacobp100** [styled-components/benchmark#1]
If anybody is good with setting up CIs, it might be of use here!

**Comment by mxstbr** [comment]
Can we maybe run https://github.com/paulirish/pwmetrics on CI? That apparently gives more consistent numbers...

**Comment by quantizor** [comment]
A few ideas:

1. Might be cool to automatically run the benchmarks after merges to master and update the README with the latest run results via templating (the resulting commit would be marked with `[skip ci]` so it doesn't loop on itself. Alternatively, we could deploy the benchmark results as a github "release".

2. Bundle size analysis for the tested libraries? Another metric that ultimately impacts performance, though only upfront.

3. Set up [greenkeeper](https://greenkeeper.io/) so we automatically get library updates without too much hassle.
